name: gen-org-contributors

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: thinkasany/organize-contributors@master
        with:
          organize_name: hellof2e
          github_token: ${{ secrets.GIT_ACTION }}
          png_path: images/contributors.png
          json_path: contributors.json
          branch: main
          commit_message: "chore: update contributors"
          excludes_list: "ImgBotApp,github-actions[bot],actions-user,imgbot[bot],dependabot[bot]"
